{{- if and .Values.valkey.metrics.enabled .Values.valkey.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: valkey
    {{- if .Values.valkey.metrics.prometheusRule.extraLabels }}
    {{- toYaml .Values.valkey.metrics.prometheusRule.extraLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.valkey.metrics.prometheusRule.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with .Values.valkey.metrics.prometheusRule.rules }}
  groups:
    - name: {{ include "valkey.fullname" $ }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}