{{- if and .Values.valkey.metrics.enabled .Values.valkey.metrics.serviceMonitor.enabled .Values.valkey.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "valkey.fullname" . }}-valkey
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/component: servicemonitor-valkey
    {{- with .Values.valkey.metrics.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.valkey.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ .Values.valkey.metrics.serviceMonitor.port }}
      {{- with .Values.valkey.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.valkey.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.valkey.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.valkey.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.valkey.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.valkey.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.valkey.metrics.serviceMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.valkey.metrics.serviceMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics-valkey
{{- end }}
---
{{- if and (eq .Values.config.mode "sentinel") .Values.sentinel.metrics.enabled .Values.sentinel.metrics.serviceMonitor.enabled .Values.sentinel.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "valkey.fullname" . }}-sentinel
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: valkey
    app.kubernetes.io/component: servicemonitor-sentinel
    {{- with .Values.sentinel.metrics.serviceMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.sentinel.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ .Values.sentinel.metrics.serviceMonitor.port }}
      {{- with .Values.sentinel.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.sentinel.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.sentinel.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.sentinel.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.sentinel.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.sentinel.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.sentinel.metrics.serviceMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.sentinel.metrics.serviceMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics-sentinel
{{- end }}
